# Generated by Django 4.2.6 on 2023-12-06 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0003_availablebookingdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
