# Generated by Django 4.2.6 on 2023-12-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0006_userprofile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('UNDEFINED', 'Brak'), ('MAN', 'Mężczyzna'), ('WOMAN', 'Kobieta')], default='UNDEFINED', max_length=10),
        ),
    ]
