# Generated by Django 4.2.6 on 2023-12-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0007_alter_userprofile_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('man', 'Mężczyzna'), ('woman', 'Kobieta')], max_length=30, null=True),
        ),
    ]
