# Generated by Django 4.2.6 on 2023-12-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0008_alter_userprofile_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('UNDEFINED', 'Brak'), ('MALE', 'Mężczyzna'), ('FEMALE', 'Kobieta')], max_length=30, null=True),
        ),
    ]
