# Generated by Django 4.2.6 on 2023-12-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0010_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablebookingdate',
            name='breakBetweenIntervals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='availablebookingdate',
            name='intervalTime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
