# Generated by Django 4.2.6 on 2023-12-20 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0011_availablebookingdate_breakbetweenintervals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='availableBookingDate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservationApp.availablebookingdate'),
        ),
    ]
