# Generated by Django 4.2.6 on 2023-12-29 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0015_alter_notification_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='content',
        ),
        migrations.AddField(
            model_name='notification',
            name='notificationType',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
